Documentation for alitv.pl
AliTVTeam/AliTV-perl-interface pull request #128
Opened 2017-04-20 22:28 UTC by greatfireball

Adds the documentation for `alitv.pl` including the description of the YML file.

2017-04-20 22:28 UTC, review-ninja commented
<a href="https://app.review.ninja/AliTVTeam/AliTV-perl-interface/pull/128" target="_blank"><img src="https://app.review.ninja/41874017/pull/128/badge" alt="ReviewNinja"/>

2017-04-21 07:59 UTC, iimog requested changes
Nice! Very good work, thanks a lot. The documentation is extensive and easy to understand due to good examples. Please fix the typos as indicated.

2017-04-21 07:59 UTC, iimog commented on README.md
> +The parameters might be a single YML file or at least to sequence
typo: to -> two

2017-04-21 07:59 UTC, iimog commented on README.md
> +The script creates the required JSON file to run AliTV. The output
run -> visualize with/import into ?

2017-04-21 07:59 UTC, iimog commented on README.md
> +The script creates the required JSON file to run AliTV. The output
or just: "to run" -> for

2017-04-21 07:59 UTC, iimog commented on README.md
> +    overwritten. Overwritting can be expicitly disabled by
typo: Overwritting -> Overwriting

2017-04-21 07:59 UTC, iimog commented on README.md
> +need to have a unique name, at least one sequence file, and
typo: need -> needs

2017-04-21 07:59 UTC, iimog commented on README.md
> +Within the genomes section, each genome has to be declared. One genome
One -> Each ?

2017-04-21 07:59 UTC, iimog commented on README.md
> +- `feature_files` keys contains different features. Each is defined as
typo: keys -> key

2017-04-21 07:59 UTC, iimog commented on README.md
> +supports three different sections:
I count four sections: genomes, tree, features, alignment

2017-04-21 07:59 UTC, iimog commented on README.md
> +This section contains of the specification of the alignment program
typo: "contains of" -> "contains"

2017-04-21 07:59 UTC, iimog commented on bin/alitv.pl
> +supports three different sections:
See above: three -> four

2017-04-21 07:59 UTC, iimog commented on bin/alitv.pl
> +supports three different sections:
Generally most of the comments from above apply to this file as well as it contains identical text in some places

2017-04-21 08:45 UTC, greatfireball commented on README.md
> +The script creates the required JSON file to run AliTV. The output
check

2017-04-21 08:45 UTC, greatfireball commented on README.md
> +    overwritten. Overwritting can be expicitly disabled by
done

2017-04-21 08:46 UTC, greatfireball commented on README.md
> +The parameters might be a single YML file or at least to sequence
check

2017-04-21 08:46 UTC, greatfireball commented on README.md
> +supports three different sections:
:) check

2017-04-21 08:47 UTC, greatfireball commented on README.md
> +Within the genomes section, each genome has to be declared. One genome
check

2017-04-21 08:48 UTC, greatfireball commented on README.md
> +- `feature_files` keys contains different features. Each is defined as
check

2017-04-21 08:49 UTC, greatfireball commented on README.md
> +This section contains of the specification of the alignment program
check

2017-04-21 08:49 UTC, greatfireball commented on bin/alitv.pl
> +supports three different sections:
derived from changed perldoc

2017-04-21 09:24 UTC, iimog approved these changes

2017-04-21 10:41 UTC, merged